name: Docker/Wildfly CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: jrschoolaccount
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'

    - name: Build .war file
      run: |
        ./mvnw clean package

    - name: Run tests
      run: |
        ./mvnw test
        
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
        
    - name: Build and test
      uses: docker/build-push-action@v6
      with:
        target: test
        load: true
          
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        target: final
        tags: ${{ env.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
